name: Java CI

on:
  push:
    branches:
      - master
      - $default-branch
      - $protected-branches
  pull_request:
    branches:
      - master
      - $default-branch
  workflow_dispatch:

permissions:
  id-token: write
  attestations: write
  contents: write
  packages: write

jobs:
  check-release-needed:
    runs-on: ubuntu-latest
    outputs:
      release_needed: ${{ steps.create_release_needed.outputs.release_needed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ (github.repository == 'JOSM/panoramax' && github.ref_type == 'branch' && github.ref_name == 'master' && github.event_name != 'schedule' && github.event_name != 'pull_request') && '0' || '10' }}

      - name: Set release needed
        id: create_release_needed
        run: |
          last_tag=$(git describe --tags --abbrev=0 --always)
          last_tag_sha=$(git show $last_tag --oneline --no-abbrev-commit | head -n1 | awk '{print $1}')
          release_needed="false"
          if [ "$last_tag_sha" == ${{ github.sha }} ]; then release_needed="true"; fi
          for file in $(git diff ${last_tag}..HEAD --name-only); do
            if [[ $file = "src/main"* ]]; then
              release_needed="true"
              break
            fi
          done
          echo "release_needed=$release_needed" >> $GITHUB_OUTPUT
  call-workflow-latest:
    needs: check-release-needed
    uses: JOSM/JOSMPluginAction/.github/workflows/ant.yml@v3
    with:
      josm-revision: ""
      java-version: 21
  call-workflow-min:
    needs: check-release-needed
    uses: JOSM/JOSMPluginAction/.github/workflows/ant.yml@v3
    with:
      josm-revision: "r19387"
      java-version: 21
      perform-revision-tagging: ${{ needs.check-release-needed.outputs.release_needed == 'true' }}

